version: '3.9'
services:
  sqlserver_service_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Teste@33344
    ports:
      - 1433:1433  
    networks:
      - db
    volumes:
      - sqlserver_data:/var/opt/mssql/data

volumes:
  sqlserver_data:
    driver: local 

networks:
  db:
    driver: bridge  
